major:
  - any: ['**/src/main/java/**', '**/src/main/kotlin/**']
  - all: ['BREAKING CHANGE']

minor:
  - any: ['**/src/main/java/**', '**/src/main/kotlin/**']
  - all: ['feat']

patch:
  - any: ['**/src/main/java/**', '**/src/main/kotlin/**']
  - all: ['fix', 'docs', 'style', 'refactor', 'perf', 'test']

documentation:
  - any: ['README.md', '**/README.md']

workflow:
  - any: ['.github/workflows/**']

i18n:
  - any: ['**/src/main/resources/translations/*.yml']