services:
  proxy-1:
    container_name: velocity-proxy-1
    image: itzg/bungeecord
    environment:
      EULA: true
      TYPE: VELOCITY
      DB_HOST: 'http://localhost:3306'
      DB_NAME: 'hyro'
      DB_PASSWORD: 'yourpassword'
    ports:
      - '25577:25577'
    volumes:
      - ./assets/server-icon.png:/server/server-icon.png
      - proxy-1:/server
    restart: unless-stopped

  lobby-1:
    container_name: paper-lobby-1
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: PAPER
      VERSION: 1.20.6
      ONLINE_MODE: false
      MEMORY: 1G
    expose:
      - 25565
    volumes:
      - lobby-1:/data
    restart: unless-stopped

volumes:
  proxy-1:
  lobby-1:
