version: '3'

services:
  megatron-database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
    - ./mongo:/data/db
    environment:
      MONGO_DATABASE: megatron-database