services:
  proxy-1:
    container_name: velocity-proxy-1
    image: itzg/bungeecord
    environment:
      EULA: true
      TYPE: VELOCITY
      MEMORY: 500M
      DB_HOST: 'http://localhost:3306'
      DB_NAME: 'hyro'
      DB_PASSWORD: 'yourpassword'
    ports:
      - '25577:25577'
    volumes:
      - proxy-1:/server
    restart: unless-stopped

  lobby-1:
    container_name: paper-lobby-1
    image: itzg/minecraft-server
    environment:
      ALLOW_NETHER: false
      DIFFICULTY: peaceful
      EULA: true
      MEMORY: 1G
      ONLINE_MODE: false
      SPAWN_MONSTERS: false
      TYPE: PAPER
      VERSION: 1.20.6
    expose:
      - 25565
    volumes:
      - lobby-1:/data
    restart: unless-stopped

volumes:
  proxy-1:
  lobby-1:
