database:
  uri:
  name:

cache:
  host:
  port:

blocked-commands:
  - '/?'
  - '/pl'
  - '/plugins'
  - '/bukkit'
  - '/reload'
  - '/rl'
  - '/stop'
  - '/spigot'
  - '/version'
  - '/ver'
  - '/help'