blank_issues_enabled: true
contact_links:
  - name: '📫 Contact us & Support'
    url: 'https://discord.gg/5yVnrtRCGb'
    about: 'Need help? We have a community of developers and contributors who can help you.'