name: 'New Content Request/Idea'
description: 'Suggest a new feature or content idea for the project'
labels: ['enhancement']
body:
  - type: input
    id: request-title
    attributes:
      label: '📚 Title or topic'
      description: 'A clear and concise title or topic for your request'
      placeholder: 'Add [...] feature'
    validations:
      required: true
  - type: textarea
    id: request-description
    attributes:
      label: '📝 Describe your request'
      description: 'A clear and concise description of what you want to happen.'
      placeholder: 'I would like to see [...]'
    validations:
      required: true
  - type: textarea
    id: request-additional
    attributes:
      label: '✏️ Additional context'
      description: 'Add any other context or screenshots about the feature request here.'
      placeholder: 'Screenshots, logs, etc.'
    validations:
      required: false