lobby-status:
  worlds:
    - world
    - test
  blocks: true # If true, player will be unable to break or place blocks
  hunger: true # If true, player will be unable to lose hunger
  damage: true # If true, player will be unable to take damage
  item-drop: true # If true, player will be unable to drop items
  item-pickup: true # If true, player will be unable to pick up items

scoreboard:
  tablist: true # If true, tablist will be displayed
  sidebar: true # If true, a sidebar will be displayed
  health: true # If true, health will be displayed

chat:
  per-world-chat: false # If true, messages will be sent only for players in the same world